name: Dockerhub Build

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: "{{defaultContext}}:dockerhub"
          platforms: linux/amd64
          tags: manavtidhana28/qmltranslation-action:latest, manavtidhana28/qmltranslation-action:${{ github.event.inputs.tag }}